version: '3.9'
services: 
  backend:
    build: .
    environment:
      DB_HOST: 34.87.87.254
      DB_PORT: 3306
      DB_DATABASE: photo-webapp
      DB_USERNAME: root
      DB_PASSWORD: password
      SECRET_KEY: secret
